/// The Ed25519 public key used to verify signed remote-config payloads
/// (Masterdoc §6.5, §22 — the public key ships in-app; the private key
/// never touches the repo and lives only as the `REMOTE_CONFIG_PRIVATE_KEY`
/// GitHub Actions secret used by `tool/sign_config.dart`).
abstract final class RemoteConfigSigningKey {
  /// The 32-byte Ed25519 public key, generated by
  /// `tool/generate_signing_key.dart` and safe to commit.
  static const List<int> publicKeyBytes = [
    15,
    17,
    21,
    228,
    200,
    221,
    33,
    80,
    154,
    224,
    45,
    244,
    193,
    155,
    29,
    183,
    15,
    12,
    215,
    8,
    214,
    135,
    235,
    73,
    138,
    153,
    64,
    120,
    173,
    52,
    82,
    63,
  ];
}
